services:
  database:
    build: ./database
    networks:
      - back-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    networks:
      - back-network
      - front-network
    depends_on:
      - database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  frontend:
    build: ./frontend
    networks:
      - front-network
    restart: unless-stopped

  httpd:
    build: ./httpd
    ports:
      - "80:80"
    networks:
      - front-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  front-network:
  back-network:

volumes:
  db-data:
